### ISSUE TITLE
Facing issue in committing multiple file in vs code.

### ISSUE THREAD

**Issue by pathakshubham21** [Zualahmed/SDLC_31_LTTS_Champs#3]
Hi team Facing issue in committing multiple file in vs code.

**Comment by Zualahmed** [comment]
can you elaborate your issue , what kind of problem your are facing.

**Comment by Zualahmed** [comment]
Predominantly there are 2 kind of file one is .c file and other one is .h file.  your .h file should contain all predefined function and data members , preprocessor and macros that will be used multiple times in different .c file.
 your .c file should contain the .h file by writing #include"filename.h".
Hope that answers your issue.

**Comment by pathakshubham21** [comment]
Yehh I followed the steps for selecting the multiple file then passing the message .
Status : Resolved
