### ISSUE TITLE
Not able to run the project on local system.

### ISSUE THREAD

**Issue by devangisingh** [Zualahmed/SDLC_31_LTTS_Champs#6]

**Comment by deepmonu** [comment]
for that you have to install gcc compiler  to compile the code

**Comment by devangisingh** [comment]
OKay!! Thank You.

**Comment by pathakshubham21** [comment]
follow the given step in mentioned in implementation readme file. Hope you will be resolved !!

**Comment by devangisingh** [comment]
Okay...Thank You Shubham.
