### ISSUE TITLE
I face issue while pushing the folder in github account through linux system

### ISSUE THREAD

**Issue by deepmonu** [Zualahmed/SDLC_31_LTTS_Champs#7]
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/Zualahmed/SDLC_31_LTTS_Champs.git/'

**Comment by devangisingh** [comment]
Hi Deepanshu
you can do the following steps to get rid of this problem
setting->developer setting->personal access token->generate new token
hope this solves the issue.

**Comment by pathakshubham21** [comment]
Hi Deepanshu,
Please go through the given you tube video "https://youtu.be/eL_0Ok_Gkas".

**Comment by deepmonu** [comment]
thank you, Issue has been resolved
